name: Build for Windows x86

on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download FFmpeg Release
        run: |
          mkdir ffmpeg
          curl -sSL -o ffmpeg.zip https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/latest/download/ffmpeg-n6.0-latest-win32-gpl-6.0.zip
          Expand-Archive -Path ffmpeg.zip -DestinationPath ffmpeg

      - name: List contents of ffmpeg directory
        run: ls -R ./ffmpeg

      - name: Move ffmpeg.exe to root
        run: mv ./ffmpeg/ffmpeg-n6.0-latest-win32-gpl-6.0/bin/ffmpeg.exe ./ffmpeg.exe

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build for Win32
        id: build-win32
        run: npm run build:win32
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Export dist directory
        if: success()  # Only proceed if the build succeeded
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: ./dist


  upload-release-asset:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact

      - name: Find file to upload
        id: find-file
        run: |
          file=$(find ./archerlink-electron/dist -type f -name "ArcherLink*")
          echo "::set-output name=file_path::$file"

      - name: Upload a file to Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find-file.outputs.file_path }}
          asset_name: ${{ steps.find-file.outputs.file_name }}
          asset_content_type: application/octet-stream
